version: "3"
services:
  database:
    image: postgres:13-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    ports:
      - 5632:5432
    volumes:
      - .docker/.data/.postgresql/13/data:/var/lib/postgresql/data
  mailcatcher:
    image: jonathanccalixto/mailcatcher:latest
    ports:
      - "1080:1080"
      - "1025:1025"
