default: &default
  adapter: postgresql
  encoding: unicode
  port: 5632
  username: postgres
  password: root
  host: localhost
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: rails_base_development
test:
  <<: *default
  database: rails_base_test

production:
  <<: *default
  database: rails_base


  